name: spotify-network
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywin32=305
  - pyzmq=25.1.2
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
